project:
  type: book
  output-dir: docs

book:
  title: "Course Notes for 431"
  author: "Thomas E. Love, Ph.D."
  date: last-modified
  reader-mode: true
  search: true
  downloads: [pdf, epub]
  output-file: "431-notes"
  chapters:
    - index.qmd
    - int_r_setup.qmd
    - 01-datascience.qmd
    - part: "Part A. Exploring Data"
      chapters:
        - 02-penguins1.qmd
        - 03-penguins2.qmd
        - 04-nhanes.qmd
        - 05-data_types.qmd
        - 06-nhanes_cc.qmd
        - 07-summarizing_quantities.qmd
        - 08-summarizing_categories.qmd
        - 09-missing_data.qmd
        - 10-nnyfs_foundations.qmd
        - 11-normality.qmd
        - 12-straightlinemodels.qmd
        - 13-correlation.qmd
        - 14-linear_trans.qmd
        - 15-crabs.qmd
        - 16-hydrate.qmd
        - 17-wcgs.qmd
    - part: "Part B. Comparing Summaries"
      chapters:
        - 18-testing_intro.qmd
        - 19-ci_for_mean.qmd
        - 20-ibuprofen_sepsis.qmd
        - 21-pairedsamples.qmd
        - 22-samplesize.qmd
        - 23-examples_2means.qmd
        - 24-anova.qmd
        - 25-one_proportion.qmd
        - 26-comparing_rates.qmd
        - 27-power_for_rates.qmd
        - 28-contingency_tables.qmd
    - part: "Part C. Building Models"
      chapters: 
        - 29-mult_reg_intro.qmd
        - 30-regr_diagnostics.qmd
        - 31-prediction_wcgs.qmd
        - 32-galapagos.qmd
        - 33-nonlinearity.qmd
        - 34-olsfits.qmd
        - 35-emp_bmi.qmd
  appendices:
    - 98_gettingdataintoR.qmd
    - 99_sessioninfo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: pulse
      dark: cyborg
    date-format: iso
    code-link: true
  pdf:
    documentclass: scrreprt
    date-format: iso
  epub: 
    date-format: iso

editor: source

