# This is the archived version of Dr. Love's Course Notes {.unnumbered}

This document is no longer in active development. Dr. Love is building new materials, but this remains as an archive of where the original notes were as of late August 2023.

# Working with These Notes {.unnumbered}

1. This document is broken down into multiple chapters. Use the table of contents on the left side of the screen to navigate between chapters, or use the right side to navigate within the current chapter.
2. You can also search the document, using an automated index.
3. Any of the code provided in the document can be copied to the clipboard using the Copy icon at the top right of the code block.

## What You'll Find Here {.unnumbered}

These Notes provided a series of examples using R to work through issues that were likely to come up in PQHS/CRSP/MPHP 431 through 2023. What you will mostly find are brief explanations of a key idea or summary, accompanied (most of the time) by R code and a demonstration of the results of applying that code.

While these Notes share some of the features of a textbook, they are neither comprehensive nor completely original. The main purpose is to give 431 students a set of common materials on which to draw during the course. In class, we will sometimes:

-   reiterate points made in this document,
-   amplify what is here,
-   simplify the presentation of things done here,
-   use new examples to show some of the same techniques,
-   refer to issues not mentioned in this document,

but what we don't do is follow these notes very precisely. We assume instead that you will read the materials and try to learn from them, just as you will attend classes and try to learn from them. We welcome feedback of all kinds on this document or anything else.

All of the code and text in these Notes is available online, and it is also possible to download a PDF version of the document from the down arrow next to the title (Notes for 431) at the top left of this screen. 
