<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Archived Course Notes for 431, version 2023 - 35&nbsp; BMI and Employment Study</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./98_gettingdataintoR.html" rel="next">
<link href="./34-olsfits.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./29-mult_reg_intro.html">Part C. Building Models</a></li><li class="breadcrumb-item"><a href="./35-emp_bmi.html"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">BMI and Employment Study</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Archived Course Notes for 431, version 2023</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="./431-archive-notes.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">This is the archived version of Dr.&nbsp;Love’s Course Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setting Up R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Part A. Exploring Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Part B. Comparing Summaries</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-testing_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ci_for_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-pairedsamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-samplesize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size and Power for Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-examples_2means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-comparing_rates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-power_for_rates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-contingency_tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Part C. Building Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-mult_reg_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-regr_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-prediction_wcgs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-galapagos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Species Found on the Galapagos Islands</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-nonlinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Introduction to Non-linear Terms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-olsfits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-emp_bmi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">BMI and Employment Study</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"><span class="header-section-number">35.1</span> Setup: Packages Used Here</a></li>
  <li>
<a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">35.2</span> The Data</a>
  <ul class="collapse">
<li><a href="#specifying-outcome-and-predictors-for-our-model" id="toc-specifying-outcome-and-predictors-for-our-model" class="nav-link" data-scroll-target="#specifying-outcome-and-predictors-for-our-model"><span class="header-section-number">35.2.1</span> Specifying Outcome and Predictors for our Model</a></li>
  <li><a href="#dealing-with-missing-predictor-values" id="toc-dealing-with-missing-predictor-values" class="nav-link" data-scroll-target="#dealing-with-missing-predictor-values"><span class="header-section-number">35.2.2</span> Dealing with Missing Predictor Values</a></li>
  </ul>
</li>
  <li><a href="#the-kitchen-sink-model" id="toc-the-kitchen-sink-model" class="nav-link" data-scroll-target="#the-kitchen-sink-model"><span class="header-section-number">35.3</span> The “Kitchen Sink” Model</a></li>
  <li>
<a href="#using-categorical-variables-factors-as-predictors" id="toc-using-categorical-variables-factors-as-predictors" class="nav-link" data-scroll-target="#using-categorical-variables-factors-as-predictors"><span class="header-section-number">35.4</span> Using Categorical Variables (Factors) as Predictors</a>
  <ul class="collapse">
<li><a href="#gender-a-binary-variable-represented-by-letters" id="toc-gender-a-binary-variable-represented-by-letters" class="nav-link" data-scroll-target="#gender-a-binary-variable-represented-by-letters"><span class="header-section-number">35.4.1</span> <code>gender</code>: A binary variable represented by letters</a></li>
  <li><a href="#employed-a-binary-variable-represented-a-10-indicator" id="toc-employed-a-binary-variable-represented-a-10-indicator" class="nav-link" data-scroll-target="#employed-a-binary-variable-represented-a-10-indicator"><span class="header-section-number">35.4.2</span> <code>employed</code>: A binary variable represented a 1/0 indicator</a></li>
  <li><a href="#alcohol-a-three-category-variable-coded-by-names" id="toc-alcohol-a-three-category-variable-coded-by-names" class="nav-link" data-scroll-target="#alcohol-a-three-category-variable-coded-by-names"><span class="header-section-number">35.4.3</span> <code>alcohol</code>: A three-category variable coded by names</a></li>
  <li><a href="#t-tests-and-multi-categorical-variables" id="toc-t-tests-and-multi-categorical-variables" class="nav-link" data-scroll-target="#t-tests-and-multi-categorical-variables"><span class="header-section-number">35.4.4</span> t tests and multi-categorical variables</a></li>
  <li><a href="#education-a-four-category-variable-coded-by-names" id="toc-education-a-four-category-variable-coded-by-names" class="nav-link" data-scroll-target="#education-a-four-category-variable-coded-by-names"><span class="header-section-number">35.4.5</span> <code>education</code>: A four-category variable coded by names</a></li>
  <li><a href="#interpreting-the-kitchen-sink-model" id="toc-interpreting-the-kitchen-sink-model" class="nav-link" data-scroll-target="#interpreting-the-kitchen-sink-model"><span class="header-section-number">35.4.6</span> Interpreting the Kitchen Sink Model</a></li>
  </ul>
</li>
  <li><a href="#scatterplot-matrix-with-categorical-predictors" id="toc-scatterplot-matrix-with-categorical-predictors" class="nav-link" data-scroll-target="#scatterplot-matrix-with-categorical-predictors"><span class="header-section-number">35.5</span> Scatterplot Matrix with Categorical Predictors</a></li>
  <li><a href="#residual-plots-when-we-have-categorical-predictors" id="toc-residual-plots-when-we-have-categorical-predictors" class="nav-link" data-scroll-target="#residual-plots-when-we-have-categorical-predictors"><span class="header-section-number">35.6</span> Residual Plots when we have Categorical Predictors</a></li>
  <li><a href="#stepwise-regression-and-categorical-predictors" id="toc-stepwise-regression-and-categorical-predictors" class="nav-link" data-scroll-target="#stepwise-regression-and-categorical-predictors"><span class="header-section-number">35.7</span> Stepwise Regression and Categorical Predictors</a></li>
  <li><a href="#pooling-results-after-multiple-imputation" id="toc-pooling-results-after-multiple-imputation" class="nav-link" data-scroll-target="#pooling-results-after-multiple-imputation"><span class="header-section-number">35.8</span> Pooling Results after Multiple Imputation</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./29-mult_reg_intro.html">Part C. Building Models</a></li><li class="breadcrumb-item"><a href="./35-emp_bmi.html"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">BMI and Employment Study</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">35</span>&nbsp; <span class="chapter-title">BMI and Employment Study</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>This chapter was developed originally in 2018 and 2019, and has only been lightly revised since. In part, I have done this to let you see some other options. One appealing feature is that this chapter (eventually) uses the <code>mice</code> package to do some multiple imputation, and work with missing data, instead of <code>naniar</code>. While we’ll have other approaches for this in 432, at least you’ll see one possibility.</p>
<section id="setup-packages-used-here" class="level2" data-number="35.1"><h2 data-number="35.1" class="anchored" data-anchor-id="setup-packages-used-here">
<span class="header-section-number">35.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">knitr</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">opts_chunk</a></span><span class="op">$</span><span class="fu">set</span><span class="op">(</span>comment <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggobi.github.io/ggally/">GGally</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/amices/mice">mice</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll also use a function from the <code>Hmisc</code> package.</p>
</section><section id="the-data" class="level2" data-number="35.2"><h2 data-number="35.2" class="anchored" data-anchor-id="the-data">
<span class="header-section-number">35.2</span> The Data</h2>
<p>A 2016 study published in <em>BMJ Open</em> looked at the differential relationship between employment status and body-mass index among middle-aged and elderly adults living in South Korea. Data from this study were available online thanks to the Dryad data package. The original data came from a nationally representative sample of 7228 participants in the Korean Longitudinal Study of Aging. I sampled these data, and did some data “rectangling” (wrangling) to build the <code>emp_bmi.csv</code> file on our web site.</p>
<p>The available data in <code>emp_bmi</code> describe 999 subjects, and included are 8 variables:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">emp_bmi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/emp_bmi.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;">Variable</th>
<th>Description</th>
<th>NA?</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>pid</code></td>
<td>subject identification number (categorical)</td>
<td>0</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>bmi</code></td>
<td>our outcome, quantitative, body-mass index</td>
<td>0</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>age</code></td>
<td>subject’s age (between 51 and 95)</td>
<td>1</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>gender</code></td>
<td>subject’s gender (male or female)</td>
<td>0</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>employed</code></td>
<td>employment status indicator (1/0)</td>
<td>1</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>married</code></td>
<td>marital status indicator (1/0)</td>
<td>1</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>alcohol</code></td>
<td>3-level factor</td>
<td>2</td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>education</code></td>
<td>4-level factor</td>
<td>5</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">Hmisc</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">describe</a></span><span class="op">(</span><span class="va">emp_bmi</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>emp_bmi 

 8  Variables      999  Observations
--------------------------------------------------------------------------------
pid 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     999        0      999        1    31774    20178     3506     6961 
     .25      .50      .75      .90      .95 
   16671    31761    46902    54635    58433 

lowest :    22    41    52    82   112, highest: 61471 61481 61532 61641 61691
--------------------------------------------------------------------------------
bmi 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     999        0      373        1    23.24    2.808    19.21    20.13 
     .25      .50      .75      .90      .95 
   21.54    23.24    24.78    26.56    27.34 

lowest : 15.6  15.63 16.22 16.44 16.53, highest: 31.11 31.24 32.05 33.5  34.67
--------------------------------------------------------------------------------
age 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     998        1       43    0.999    66.29    11.56       52       53 
     .25      .50      .75      .90      .95 
      57       66       74       81       83 

lowest : 51 52 53 54 55, highest: 89 90 92 93 95
--------------------------------------------------------------------------------
gender 
       n  missing distinct 
     999        0        2 
                        
Value      female   male
Frequency     570    429
Proportion  0.571  0.429
--------------------------------------------------------------------------------
employed 
       n  missing distinct     Info      Sum     Mean      Gmd 
     998        1        2    0.723      404   0.4048   0.4824 

--------------------------------------------------------------------------------
married 
       n  missing distinct     Info      Sum     Mean      Gmd 
     998        1        2    0.548      758   0.7595   0.3657 

--------------------------------------------------------------------------------
alcohol 
       n  missing distinct 
     997        2        3 
                                                                      
Value                  alcohol dependent                 heavy drinker
Frequency                             45                           306
Proportion                         0.045                         0.307
                                        
Value      normal drinker or non-drinker
Frequency                            646
Proportion                         0.648
--------------------------------------------------------------------------------
education 
       n  missing distinct 
     994        5        4 
                                                                  
Value      1 elem school grad or lower        2 middle school grad
Frequency                          421                         180
Proportion                       0.424                       0.181
                                                                  
Value               3 high school grad    4 college grad or higher
Frequency                          292                         101
Proportion                       0.294                       0.102
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<section id="specifying-outcome-and-predictors-for-our-model" class="level3" data-number="35.2.1"><h3 data-number="35.2.1" class="anchored" data-anchor-id="specifying-outcome-and-predictors-for-our-model">
<span class="header-section-number">35.2.1</span> Specifying Outcome and Predictors for our Model</h3>
<p>In the original study, a key goal was to understand the relationship between employment and body-mass index. Our goal in this example will be to create a model to predict <code>bmi</code> focusing on employment status (so our key predictor is <code>employed</code>) while accounting for the additional predictors <code>age</code>, <code>gender</code>, <code>married</code>, <code>alcohol</code> and <code>education</code>. A natural thing to do would be to consider interactions of these predictor variables (for example, does the relationship between <code>bmi</code> and <code>employed</code> change when comparing men to women?) but we’ll postpone that discussion until 432.</p>
</section><section id="dealing-with-missing-predictor-values" class="level3" data-number="35.2.2"><h3 data-number="35.2.2" class="anchored" data-anchor-id="dealing-with-missing-predictor-values">
<span class="header-section-number">35.2.2</span> Dealing with Missing Predictor Values</h3>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://amices.org/mice/reference/md.pattern.html">md.pattern</a></span><span class="op">(</span><span class="va">emp_bmi</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="35-emp_bmi_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    pid bmi gender age employed married alcohol education   
990   1   1      1   1        1       1       1         1  0
5     1   1      1   1        1       1       1         0  1
1     1   1      1   1        1       1       0         1  1
1     1   1      1   1        1       0       1         1  1
1     1   1      1   1        0       1       1         1  1
1     1   1      1   0        1       1       0         1  2
      0   0      0   1        1       1       2         5 10</code></pre>
</div>
</div>
<p>We will eventually build a model to predict <code>bmi</code> using all of the other variables besides <code>pid</code>. So we’ll eventually have to account for the 9 people with missing values (one of whom has two missing values, as we see above.) What I’m going to do in this example is to first build a complete-case analysis on the 990 subjects without missing values and then, later, do multiple imputation to account for the 9 subjects with missing values (and their 10 actual missing values) sensibly.</p>
<p>I’ll put the “complete cases” data set of 990 subjects in <code>emp_bmi_noNA</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">emp_bmi_noNA</span> <span class="op">&lt;-</span> <span class="va">emp_bmi</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">emp_bmi_noNA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 990 × 8
     pid   bmi   age gender employed married alcohol                   education
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;chr&gt;    
 1    22  20.8    58 male          1       1 heavy drinker             4 colleg…
 2    41  21.4    76 female        0       1 normal drinker or non-dr… 1 elem s…
 3    52  20.9    66 female        1       1 heavy drinker             1 elem s…
 4    82  23.7    67 male          1       1 alcohol dependent         2 middle…
 5   112  25.5    63 female        0       1 heavy drinker             1 elem s…
 6   181  20.5    51 female        1       1 heavy drinker             3 high s…
 7   182  25.3    51 male          1       1 alcohol dependent         3 high s…
 8   411  20.8    66 female        1       1 normal drinker or non-dr… 2 middle…
 9   491  20.8    64 female        0       1 normal drinker or non-dr… 3 high s…
10   531  24.3    84 female        0       0 normal drinker or non-dr… 1 elem s…
# ℹ 980 more rows</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      pid       bmi       age    gender  employed   married   alcohol education 
        0         0         0         0         0         0         0         0 </code></pre>
</div>
</div>
</section></section><section id="the-kitchen-sink-model" class="level2" data-number="35.3"><h2 data-number="35.3" class="anchored" data-anchor-id="the-kitchen-sink-model">
<span class="header-section-number">35.3</span> The “Kitchen Sink” Model</h2>
<p>A “kitchen sink” model includes all available predictors.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ebmodel.1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> </span>
<span>                    <span class="va">alcohol</span> <span class="op">+</span> <span class="va">education</span>, data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ebmodel.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + gender + employed + married + alcohol + 
    education, data = emp_bmi_noNA)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7033 -1.6057 -0.0494  1.4992 11.7303 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          26.15391    0.88356  29.601  &lt; 2e-16 ***
age                                  -0.04260    0.01065  -3.998 6.86e-05 ***
gendermale                            0.29811    0.20271   1.471   0.1417    
employed                             -0.45761    0.19153  -2.389   0.0171 *  
married                               0.09438    0.21280   0.444   0.6575    
alcoholheavy drinker                  0.25317    0.40727   0.622   0.5343    
alcoholnormal drinker or non-drinker  0.14121    0.40766   0.346   0.7291    
education2 middle school grad        -0.28862    0.24020  -1.202   0.2298    
education3 high school grad          -0.50123    0.22192  -2.259   0.0241 *  
education4 college grad or higher    -0.79862    0.31068  -2.571   0.0103 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.513 on 980 degrees of freedom
Multiple R-squared:  0.02251,   Adjusted R-squared:  0.01353 
F-statistic: 2.508 on 9 and 980 DF,  p-value: 0.007716</code></pre>
</div>
</div>
</section><section id="using-categorical-variables-factors-as-predictors" class="level2" data-number="35.4"><h2 data-number="35.4" class="anchored" data-anchor-id="using-categorical-variables-factors-as-predictors">
<span class="header-section-number">35.4</span> Using Categorical Variables (Factors) as Predictors</h2>
<p>We have six predictors here, and five of them are categorical. Note that R recognizes each kind of variable in this case and models them appropriately. Let’s look at the coefficients of our model.</p>
<section id="gender-a-binary-variable-represented-by-letters" class="level3" data-number="35.4.1"><h3 data-number="35.4.1" class="anchored" data-anchor-id="gender-a-binary-variable-represented-by-letters">
<span class="header-section-number">35.4.1</span> <code>gender</code>: A binary variable represented by letters</h3>
<p>The <code>gender</code> variable contains the two categories: male and female, and R recognizes this as a factor. When building a regression model with such a variable, R assigns the first of the two levels of the factor to the baseline, and includes in the model an indicator variable for the second level. By default, R assigns each factor a level order alphabetically.</p>
<p>So, in this case, we have:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">is.factor</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p>As you see in the model, the <code>gender</code> information is captured by the indicator variable <code>gendermale</code>, which is 1 when <code>gender = male</code> and 0 otherwise.</p>
<p>So, when our model includes:</p>
<pre><code>Coefficients:     Estimate Std. Error t value Pr(&gt;|t|)    
gendermale         0.29811    0.20271   1.471   0.1417    </code></pre>
<p>this means that a male subject is predicted to have an outcome that is 0.29811 points higher than a female subject, if they have the same values of all of the other predictors.</p>
<p>Note that if we wanted to switch the levels so that “male” came first (and so that R would use “male” as the baseline category and “female” as the 1 value in an indicator), we could do so with the <code>forcats</code> package and the <code>fct_relevel</code> command. Building a model with this version of <code>gender</code> will simply reverse the sign of our indicator variable, but not change any of the other output.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">gender.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">gender</span>, <span class="st">"male"</span>, <span class="st">"female"</span><span class="op">)</span></span>
<span><span class="va">revised.model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender.2</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> </span>
<span>                    <span class="va">alcohol</span> <span class="op">+</span> <span class="va">education</span>, data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">revised.model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + gender.2 + employed + married + alcohol + 
    education, data = emp_bmi_noNA)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7033 -1.6057 -0.0494  1.4992 11.7303 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                          26.45202    0.94648  27.948  &lt; 2e-16 ***
age                                  -0.04260    0.01065  -3.998 6.86e-05 ***
gender.2female                       -0.29811    0.20271  -1.471   0.1417    
employed                             -0.45761    0.19153  -2.389   0.0171 *  
married                               0.09438    0.21280   0.444   0.6575    
alcoholheavy drinker                  0.25317    0.40727   0.622   0.5343    
alcoholnormal drinker or non-drinker  0.14121    0.40766   0.346   0.7291    
education2 middle school grad        -0.28862    0.24020  -1.202   0.2298    
education3 high school grad          -0.50123    0.22192  -2.259   0.0241 *  
education4 college grad or higher    -0.79862    0.31068  -2.571   0.0103 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.513 on 980 degrees of freedom
Multiple R-squared:  0.02251,   Adjusted R-squared:  0.01353 
F-statistic: 2.508 on 9 and 980 DF,  p-value: 0.007716</code></pre>
</div>
</div>
<p>Note that the two categories here need to be both <em>mutually exclusive</em> (a subject cannot be in more than one category) and <em>collectively exhaustive</em> (all subjects must fit into this set of categories) in order to work properly as a regression predictor.</p>
</section><section id="employed-a-binary-variable-represented-a-10-indicator" class="level3" data-number="35.4.2"><h3 data-number="35.4.2" class="anchored" data-anchor-id="employed-a-binary-variable-represented-a-10-indicator">
<span class="header-section-number">35.4.2</span> <code>employed</code>: A binary variable represented a 1/0 indicator</h3>
<p>The <code>employed</code> and <code>married</code> variables are each described using an indicator variable, which is 1 if the condition of interest holds and 0 if it does not. R doesn’t recognize this as a factor, but rather as a quantitative variable. However, this is no problem for modeling, where we just need to remember that if <code>employed</code> = 1, the subject is employed, and if <code>employed</code> = 0, the subject is not employed, to interpret the results. The same approach is used for <code>married</code>.</p>
<pre><code>Coefficients:    Estimate Std. Error t value Pr(&gt;|t|)    
employed         -0.45761    0.19153  -2.389   0.0171 *  
married           0.09438    0.21280   0.444   0.6575    </code></pre>
<p>So, in our model, if subject A is employed, they are expected to have an outcome that is 0.46 points lower (-0.46 points higher) than subject B who is not employed but otherwise identical to subject A.</p>
<p>Similarly, if subject X is married, and subject Y is unmarried, but they otherwise have the same values of all predictors, then our model will predict a <code>bmi</code> for X that is 0.094 points higher than for Y.</p>
</section><section id="alcohol-a-three-category-variable-coded-by-names" class="level3" data-number="35.4.3"><h3 data-number="35.4.3" class="anchored" data-anchor-id="alcohol-a-three-category-variable-coded-by-names">
<span class="header-section-number">35.4.3</span> <code>alcohol</code>: A three-category variable coded by names</h3>
<p>Our <code>alcohol</code> information divides subjects into three categories, which are:</p>
<ul>
<li>normal drinker or non-drinker</li>
<li>heavy drinker</li>
<li>alcohol dependent</li>
</ul>
<p>R builds a model using <span class="math inline">\(k-1\)</span> predictors to describe a variable with <span class="math inline">\(k\)</span> levels. As mentioned previously, R selects a baseline category when confronted with a factor variable, and it always selects the first level as the baseline. The levels are sorted alphabetically, unless we tell R to sort them some other way. So, we have</p>
<pre><code>Coefficients:                        Estimate Std. Error t value Pr(&gt;|t|)    
alcoholheavy drinker                  0.25317    0.40727   0.622   0.5343    
alcoholnormal drinker or non-drinker  0.14121    0.40766   0.346   0.7291    </code></pre>
<p>How do we interpret this?</p>
<ul>
<li>Suppose subject A is alcohol dependent, B is a heavy drinker and C is a normal drinker or non-drinker, but subjects A-C have the same values of all other predictors.</li>
<li>Our model predicts that B would have a BMI that is 0.25 points higher than A.</li>
<li>Our model predicts that C would have a BMI that is 0.14 points higher than A.</li>
</ul>
<p>A good way to think about this…</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th style="text-align: right;">Subject</th>
<th>Status</th>
<th style="text-align: right;">alcoholheavy drinker</th>
<th style="text-align: right;">alcoholnormal drinker or non-drinker</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">A</td>
<td>alcohol dependent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">B</td>
<td>heavy drinker</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">C</td>
<td>normal drinker or non-drinker</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>and so, with two variables, we cover each of these three possible <code>alcohol</code> levels.</p>
<p>When we have an ordered variable like this one, we usually want the baseline category to be at either end of the scale (either the highest or the lowest, but not something in the middle.) Another good idea in many settings is to use as the baseline category the most common category. Here, the baseline R chose was “alcohol dependent” which is the least common category, so I might want to use the <code>fct_relevel</code> function again to force R to choose, say, normal drinker/non-drinker as the baseline category.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">alcohol.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span><span class="op">$</span><span class="va">alcohol</span>, </span>
<span>           <span class="st">"normal drinker or non-drinker"</span>, <span class="st">"heavy drinker"</span><span class="op">)</span></span>
<span><span class="va">revised.model.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> </span>
<span>                    <span class="va">alcohol.2</span> <span class="op">+</span> <span class="va">education</span>, data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">revised.model.2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + gender + employed + married + alcohol.2 + 
    education, data = emp_bmi_noNA)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7033 -1.6057 -0.0494  1.4992 11.7303 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       26.29512    0.82860  31.734  &lt; 2e-16 ***
age                               -0.04260    0.01065  -3.998 6.86e-05 ***
gendermale                         0.29811    0.20271   1.471   0.1417    
employed                          -0.45761    0.19153  -2.389   0.0171 *  
married                            0.09438    0.21280   0.444   0.6575    
alcohol.2heavy drinker             0.11196    0.19647   0.570   0.5689    
alcohol.2alcohol dependent        -0.14121    0.40766  -0.346   0.7291    
education2 middle school grad     -0.28862    0.24020  -1.202   0.2298    
education3 high school grad       -0.50123    0.22192  -2.259   0.0241 *  
education4 college grad or higher -0.79862    0.31068  -2.571   0.0103 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.513 on 980 degrees of freedom
Multiple R-squared:  0.02251,   Adjusted R-squared:  0.01353 
F-statistic: 2.508 on 9 and 980 DF,  p-value: 0.007716</code></pre>
</div>
</div>
<p>How do we interpret this revised model?</p>
<ul>
<li>Again, subject A is alcohol dependent, B is a heavy drinker and C is a normal drinker or non-drinker, but subjects A-C have the same values of all other predictors.</li>
<li>Our model predicts that B would have a BMI that is 0.11 points higher than C.</li>
<li>Our model predicts that A would have a BMI that is 0.14 points lower than C.</li>
</ul>
<p>So, those are the same conclusions, just rephrased.</p>
</section><section id="t-tests-and-multi-categorical-variables" class="level3" data-number="35.4.4"><h3 data-number="35.4.4" class="anchored" data-anchor-id="t-tests-and-multi-categorical-variables">
<span class="header-section-number">35.4.4</span> t tests and multi-categorical variables</h3>
<p>The usual “last predictor in” t test works perfectly for binary factors, but suppose we have a factor like <code>alcohol</code> which is represented by two different indicator variables. If we want to know whether the <code>alcohol</code> information, as a group, adds statistically significant value to the model that includes all of the other predictors, then our best strategy is to compare two models - one with the alcohol information, and one without.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.with.a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">alcohol</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">education</span>, </span>
<span>                   data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="va">model.no.a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">education</span>, </span>
<span>                 data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model.with.a</span>, <span class="va">model.no.a</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: bmi ~ age + gender + alcohol + employed + married + education
Model 2: bmi ~ age + gender + employed + married + education
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    980 6189.9                           
2    982 6193.6 -2   -3.6288 0.2873 0.7504</code></pre>
</div>
</div>
<p>The <em>p</em> value for both of the indicator variables associated with <code>alcohol</code> combined is 0.75, according to an ANOVA F test with 2 degrees of freedom.</p>
<p>Note that we can get the same information from an ANOVA table of the larger model if we add the <code>alcohol</code> predictor to the model last.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">education</span> <span class="op">+</span> <span class="va">alcohol</span>, </span>
<span>         data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
age         1   55.5  55.510  8.7884 0.003105 **
gender      1    0.4   0.369  0.0585 0.809000   
employed    1   30.7  30.733  4.8657 0.027626 * 
married     1    0.4   0.374  0.0592 0.807746   
education   3   51.9  17.311  2.7408 0.042202 * 
alcohol     2    3.6   1.814  0.2873 0.750382   
Residuals 980 6189.9   6.316                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Again, we see <em>p</em> for the two <code>alcohol</code> indicators is 0.75.</p>
</section><section id="education-a-four-category-variable-coded-by-names" class="level3" data-number="35.4.5"><h3 data-number="35.4.5" class="anchored" data-anchor-id="education-a-four-category-variable-coded-by-names">
<span class="header-section-number">35.4.5</span> <code>education</code>: A four-category variable coded by names</h3>
<p>The <code>education</code> variable’s codes are a little better designed. By preceding the text with a number for each code, we force R to attend to the level order we want to see.</p>
<pre><code>Coefficients:                     Estimate Std. Error t value Pr(&gt;|t|)    
education2 middle school grad     -0.28862    0.24020  -1.202   0.2298    
education3 high school grad       -0.50123    0.22192  -2.259   0.0241 *  
education4 college grad or higher -0.79862    0.31068  -2.571   0.0103 *  </code></pre>
<p>Since we have four education levels, we need those three indicator variables.</p>
<ul>
<li>
<code>education2 middle school grad</code> is 1 if the subject is a middle school graduate, and 0 if they have some other status</li>
<li>
<code>education3 high school grad</code> is 1 if the subject is a high school graduate, and 0 if they have some other status</li>
<li>
<code>education4 college grad or higher</code> is 1 if the subject is a college graduate or has more education, and 0 if they have some other status.</li>
<li>So the subjects with only elementary school or lower education are represented by zeros in all three indicators.</li>
</ul>
<p>Suppose we have four subjects now, with the same values of all other predictors, but different levels of education.</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;">Subject</th>
<th>Education</th>
<th style="text-align: center;">Estimated BMI</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td>elementary school or less</td>
<td style="text-align: center;">A</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td>middle school grad</td>
<td style="text-align: center;">A - 0.289</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td>high school grad</td>
<td style="text-align: center;">A - 0.501</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td>college grad</td>
<td style="text-align: center;">A - 0.799</td>
</tr>
</tbody>
</table>
<p>Note that the four categories are <em>mutually exclusive</em> (a subject cannot be in more than one category) and <em>collectively exhaustive</em> (all subjects must fit into this set of categories.) As we have seen, this is a requirement of categorical variables in a regression analysis.</p>
<p>Let’s run the ANOVA test for the <code>education</code> information captured in those three indicator variables…</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> <span class="va">alcohol</span> <span class="op">+</span> <span class="va">education</span>, </span>
<span>         data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
age         1   55.5  55.510  8.7884 0.003105 **
gender      1    0.4   0.369  0.0585 0.809000   
employed    1   30.7  30.733  4.8657 0.027626 * 
married     1    0.4   0.374  0.0592 0.807746   
alcohol     2    3.5   1.750  0.2771 0.758055   
education   3   52.1  17.354  2.7476 0.041820 * 
Residuals 980 6189.9   6.316                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>So, as a group, the three indicator variables add statistically significant predictive value at the 5% significance level, since the F test for those three variables has <em>p</em> = 0.042</p>
</section><section id="interpreting-the-kitchen-sink-model" class="level3" data-number="35.4.6"><h3 data-number="35.4.6" class="anchored" data-anchor-id="interpreting-the-kitchen-sink-model">
<span class="header-section-number">35.4.6</span> Interpreting the Kitchen Sink Model</h3>
<p>So, again, here’s our model.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ebmodel.1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> <span class="va">married</span> <span class="op">+</span> </span>
<span>                    <span class="va">alcohol</span> <span class="op">+</span> <span class="va">education</span>, data <span class="op">=</span> <span class="va">emp_bmi_noNA</span><span class="op">)</span></span>
<span><span class="va">ebmodel.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + gender + employed + married + alcohol + 
    education, data = emp_bmi_noNA)

Coefficients:
                         (Intercept)                                   age  
                            26.15391                              -0.04260  
                          gendermale                              employed  
                             0.29811                              -0.45761  
                             married                  alcoholheavy drinker  
                             0.09438                               0.25317  
alcoholnormal drinker or non-drinker         education2 middle school grad  
                             0.14121                              -0.28862  
         education3 high school grad     education4 college grad or higher  
                            -0.50123                              -0.79862  </code></pre>
</div>
</div>
<p>If we wanted to predict a BMI level for a new subject like the ones used in the development of this model, that prediction would be:</p>
<ul>
<li>26.15</li>
<li>minus 0.426 times the subject’s <code>age</code>
</li>
<li>plus 0.298 if the subject’s <code>gender</code> was <code>male</code>
</li>
<li>minus 0.458 if the subject’s employment status was <code>employed</code>
</li>
<li>plus 0.253 if the subject’s <code>alcohol</code> classification was <code>heavy drinker</code>
</li>
<li>plus 0.141 if the subject’s <code>alcohol</code> classification was <code>normal drinker or non-drinker</code>
</li>
<li>minus 0.289 if the subject’s <code>education</code> classification was <code>2 middle school grad</code>
</li>
<li>minus 0.501 if the subject’s <code>education</code> classification was <code>3 high school grad</code>
</li>
<li>minus 0.799 if the subject’s <code>education</code> classification was <code>4 college grad or higher</code>
</li>
</ul></section></section><section id="scatterplot-matrix-with-categorical-predictors" class="level2" data-number="35.5"><h2 data-number="35.5" class="anchored" data-anchor-id="scatterplot-matrix-with-categorical-predictors">
<span class="header-section-number">35.5</span> Scatterplot Matrix with Categorical Predictors</h2>
<p>Let’s look at a scatterplot matrix of a few key predictors, with my favorite approach (at least for quantitative predictors)…</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggobi.github.io/ggally/reference/ggpairs.html">ggpairs</a></span><span class="op">(</span><span class="va">emp_bmi_noNA</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">gender</span>, <span class="va">employed</span>, <span class="va">education</span>, <span class="va">bmi</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="35-emp_bmi_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="residual-plots-when-we-have-categorical-predictors" class="level2" data-number="35.6"><h2 data-number="35.6" class="anchored" data-anchor-id="residual-plots-when-we-have-categorical-predictors">
<span class="header-section-number">35.6</span> Residual Plots when we have Categorical Predictors</h2>
<p>Here are the main residual plots from the kitchen sink model <code>ebmodel.1</code> defined previously.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">ebmodel.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="35-emp_bmi_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sometimes, in small samples, the categorical variables will make the regression residuals line up in somewhat strange patterns. But in this case, there’s no real problem. The use of categorical variables also has some impact on leverage, as it’s hard for a subject to be a serious outlier in terms of a predictor if that predictor only has a few possible levels.</p>
</section><section id="stepwise-regression-and-categorical-predictors" class="level2" data-number="35.7"><h2 data-number="35.7" class="anchored" data-anchor-id="stepwise-regression-and-categorical-predictors">
<span class="header-section-number">35.7</span> Stepwise Regression and Categorical Predictors</h2>
<p>When R does backwards elimination for stepwise model selection, it makes decisions about each categorical variable as in/out across all of the indicator variables simultaneously, as you’d hope.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">ebmodel.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=1834.64
bmi ~ age + gender + employed + married + alcohol + education

            Df Sum of Sq    RSS    AIC
- alcohol    2     3.629 6193.6 1831.2
- married    1     1.243 6191.2 1832.8
&lt;none&gt;                   6189.9 1834.6
- gender     1    13.660 6203.6 1834.8
- education  3    52.063 6242.0 1836.9
- employed   1    36.057 6226.0 1838.4
- age        1   100.976 6290.9 1848.7

Step:  AIC=1831.22
bmi ~ age + gender + employed + married + education

            Df Sum of Sq    RSS    AIC
- married    1     1.026 6194.6 1829.4
&lt;none&gt;                   6193.6 1831.2
- gender     1    19.071 6212.6 1832.3
- education  3    51.934 6245.5 1833.5
- employed   1    34.736 6228.3 1834.8
- age        1   108.599 6302.2 1846.4

Step:  AIC=1829.39
bmi ~ age + gender + employed + education

            Df Sum of Sq    RSS    AIC
&lt;none&gt;                   6194.6 1829.4
- gender     1    22.169 6216.7 1830.9
- education  3    51.282 6245.9 1831.5
- employed   1    34.390 6229.0 1832.9
- age        1   125.431 6320.0 1847.2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ age + gender + employed + education, data = emp_bmi_noNA)

Coefficients:
                      (Intercept)                                age  
                         26.50206                           -0.04459  
                       gendermale                           employed  
                          0.34057                           -0.44571  
    education2 middle school grad        education3 high school grad  
                         -0.28787                           -0.49772  
education4 college grad or higher  
                         -0.79037  </code></pre>
</div>
</div>
<p>Note that the stepwise approach first drops two degrees of freedom (two indicator variables) for <code>alcohol</code> and then drops the one degree of freedom for <code>married</code> before it settles on a model with <code>age</code>, <code>gender</code>, <code>education</code> and <code>employed</code>.</p>
</section><section id="pooling-results-after-multiple-imputation" class="level2" data-number="35.8"><h2 data-number="35.8" class="anchored" data-anchor-id="pooling-results-after-multiple-imputation">
<span class="header-section-number">35.8</span> Pooling Results after Multiple Imputation</h2>
<p>As mentioned earlier, having built a model using complete cases, we should probably investigate the impact of multiple imputation on the missing observations. We’ll fit 100 imputations using the <code>emp_bmi</code> data and then fit a pooled regression model across those imputations.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">emp_bmi_mi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://amices.org/mice/reference/mice.html">mice</a></span><span class="op">(</span><span class="va">emp_bmi</span>, m <span class="op">=</span> <span class="fl">100</span>, maxit <span class="op">=</span> <span class="fl">5</span>, </span>
<span>                   printFlag <span class="op">=</span> <span class="cn">FALSE</span>, seed <span class="op">=</span> <span class="fl">4312021</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we’ll fit the pooled kitchen sink regression model to these imputed data sets and pool them.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.empbmi.mi</span> <span class="op">&lt;-</span> </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">emp_bmi_mi</span>, <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bmi</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">employed</span> <span class="op">+</span> </span>
<span>                            <span class="va">married</span> <span class="op">+</span> <span class="va">alcohol</span> <span class="op">+</span> <span class="va">education</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://amices.org/mice/reference/pool.html">pool</a></span><span class="op">(</span><span class="va">model.empbmi.mi</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   term    estimate  std.error  statistic
1                           (Intercept) 26.15304370 0.88053709 29.7012402
2                                   age -0.04258223 0.01063989 -4.0021319
3                            gendermale  0.29794032 0.20237455  1.4722223
4                              employed -0.45695506 0.19112904 -2.3908196
5                               married  0.09430912 0.21247583  0.4438581
6                  alcoholheavy drinker  0.25298858 0.40270904  0.6282168
7  alcoholnormal drinker or non-drinker  0.14108076 0.40341263  0.3497182
8         education2 middle school grad -0.28861113 0.23994418 -1.2028261
9           education3 high school grad -0.50119826 0.22138848 -2.2638859
10    education4 college grad or higher -0.79852096 0.30947717 -2.5802258
        df       p.value
1  979.908 9.190979e-139
2  979.908  6.750699e-05
3  979.908  1.412819e-01
4  979.908  1.699872e-02
5  979.908  6.572432e-01
6  979.908  5.300083e-01
7  979.908  7.266253e-01
8  979.908  2.293342e-01
9  979.908  2.379907e-02
10 979.908  1.001814e-02</code></pre>
</div>
</div>
<p>OK. That’s it for now.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./34-olsfits.html" class="pagination-link" aria-label="Using `ols` to fit linear models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./98_gettingdataintoR.html" class="pagination-link" aria-label="Getting Data Into R">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>